services:

    admin_lite.dropzone.twig_extension:
        class: DigipolisGent\AdminLteBundle\Twig\DropzoneExtension
        arguments:
            - '@router'
        tags:
            - { name: twig.extension }

    admin_lte.widget.manager:
        class: DigipolisGent\AdminLteBundle\Widget\WidgetManager

    admin_lte.widget.twig_extension:
        class: DigipolisGent\AdminLteBundle\Twig\WidgetExtension
        arguments:
            - '@admin_lte.widget.manager'
        tags:
            - { name: twig.extension }
